### ISSUE TITLE
移除所有 Pods 文件夹、Podfile.lock、DemoA.xcworkspace

### ISSUE THREAD

**Issue by jiaxinwang** [RNTD/humbleadmin-SDK-iOS-Samples#4]
注意查看：
[ OC .gitignore] (https://github.com/github/gitignore/blob/master/Objective-C.gitignore)
Line 31 
以及
https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

上传时的状态应该是：
- 执行过 pods init
- 编辑过 Podfile

**但是没有执行 pods install / pods update**
**pods install / pods update 产生的文件，随版本不同是有差别的，如果我们上传的高版本pods，高xcode版本的项目，在用户的机器上可能会出现问题**

**Comment by lichang0716** [comment]
已更新
